# vim: set noexpandtab shiftwidth=8 tabstop=8:
# 
# tests/dir/makefile
#
# makefile - file to make and runs tests

CXX = g++
CXXFLAGS = -Wall -g -I../..
LDFLAGS =

include ../subdir.mk

test.o: ../../Direction.h
